### ISSUE TITLE
adding the tape firmware code broke some of the parsing code.

### ISSUE THREAD

**Issue by WildOne69** [lateralblast/oort#10]
adding the tape firmware code broke some of the parsing code:

so i ask for the T1000 (aka Sun Fire T1000) and i also get the Storagetek 10000 firmware.

and

i ask for the T2000 and i get a hang and then i get the following:

example:
mes-MacBook-Pro-4:oort me$ ./oort.rb -n T1000
T1000:
Sun Fire T1000 Sun System Firmware Update Hypervisor 1.1.3 OBP 4.20.4 POST 4.20.5
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=122431-05
https://getupdates.oracle.com/all_unsigned/122431-05.zip
Sun Fire T1000 Sun System Firmware Update Hypervisor 1.2.5 OBP 4.23.6 POST 4.23.6
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=123481-04
https://getupdates.oracle.com/all_unsigned/123481-04.zip
Sun Fire T1000 Sun System Firmware Update APL Hypervisor 1.3.4 OBP 4.25.12 POST 4.25.12
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=124751-07
https://getupdates.oracle.com/all_unsigned/124751-07.zip
Sun Fire T1000 Sun System Firmware Update APL LDOMS Hypervisor 1.4.1 OBP 4.26.1 POST 4.26.0
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=126400-02
https://getupdates.oracle.com/all_unsigned/126400-02.zip
Sun Fire T1000 Sun System Firmware Update  LDOMS AP OBP 4.27.11 Hypervisor 1.5.6 POST 4.27.11
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=127577-03
https://getupdates.oracle.com/all_unsigned/127577-03.zip
Sun Fire T1000 Sun System Firmware Update  LDOMS AP OBP 4.29.0.a Hypervisor 1.6.7.a POST 4.29.0.a
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=136928-05
https://getupdates.oracle.com/all_unsigned/136928-05.zip
Sun StorageTek T10000A Tape 1.48.105
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=148369-01
Sun StorageTek T10000B Tape 1.48.205
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=148433-01

./oort -n T2000
T2000:
Sun Fire T2000 Sun System Firmware Update Hypervisor 1.1.4 OBP 4.20.6 POST 4.20.6
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=122430-06
https://getupdates.oracle.com/all_unsigned/122430-06.zip
Sun Fire T2000 Sun System Firmware Update Hypervisor 1.2.3 OBP 4.23.4 POST 4.23.4
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=123482-03
https://getupdates.oracle.com/all_unsigned/123482-03.zip
./oort.rb:1708:in `readlines': No such file or directory @ rb_sysopen - /Users/me/oort/data/html/123483-01.html (Errno::ENOENT)
	from ./oort.rb:1708:in `get_aru_no'
	from ./oort.rb:1763:in `get_oracle_readme_url'
	from ./oort.rb:1739:in `get_obp_ver'
	from ./oort.rb:2171:in `block in print_output'
	from ./oort.rb:2154:in `each'
	from ./oort.rb:2154:in `print_output'
	from ./oort.rb:2226:in `handle_fw_output'
	from ./oort.rb:2561:in `<main>'

**Comment by richardatlateralblast** [comment]
Made model searches a little more strict, which will fix the T1000 problem

Will look into the other T2000 problem

**Comment by richardatlateralblast** [comment]
Fixed:

./oort.rb -n T2000
T2000:
Sun Fire T2000 Sun System Firmware Update Hypervisor 1.1.4 OBP 4.20.6 POST 4.20.6
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=122430-06
https://getupdates.oracle.com/all_unsigned/122430-06.zip
Sun Fire T2000 Sun System Firmware Update Hypervisor 1.2.3 OBP 4.23.4 POST 4.23.4
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=123482-03
https://getupdates.oracle.com/all_unsigned/123482-03.zip
Netra T2000 Sun System Firmware Update
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=123483-01
https://getupdates.oracle.com/all_unsigned/123483-01.zip
Sun Fire T2000 Sun System Firmware Update APL Hypervisor 1.3.4 OBP 4.25.12 POST 4.25.12
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=124750-08
https://getupdates.oracle.com/all_unsigned/124750-08.zip
Netra T2000 Sun System Firmware Update picl scadm Hypervisor 1.3.4 OBP 4.25.12 POST 4.25.12
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=124753-03
https://getupdates.oracle.com/all_unsigned/124753-03.zip
Sun Fire T2000 Sun System Firmware Update APL LDOMS Hypervisor 1.4.1 OBP 4.26.1 POST 4.26.0
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=126399-02
https://getupdates.oracle.com/all_unsigned/126399-02.zip
Netra T2000 Sun System Firmware Update  LDOMS Hypervisor 1.4.1 OBP 4.26.1 POST 4.26.0
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=126401-02
https://getupdates.oracle.com/all_unsigned/126401-02.zip
Sun Fire T2000 Sun System Firmware Update  LDOMS AP OBP 4.27.11 Hypervisor 1.5.6 POST 4.27.11
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=127576-03
https://getupdates.oracle.com/all_unsigned/127576-03.zip
Netra T2000 Sun System Firmware Update  LDOMS OBP 4.27.11 Hypervisor 1.5.6 POST 4.27.11
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=127578-03
https://getupdates.oracle.com/all_unsigned/127578-03.zip
Sun Fire T2000 Sun System Firmware Update  LDOMS AP OBP 4.29.0.a Hypervisor 1.6.7.a POST 4.29.0.a
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=136927-05
https://getupdates.oracle.com/all_unsigned/136927-05.zip
Netra T2000 Sun System Firmware Update  LDOMS APL OBP 4.29.0.a Hypervisor 1.6.7.a POST 4.29.0.a
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=136929-05
https://getupdates.oracle.com/all_unsigned/136929-05.zip

**Comment by WildOne69** [comment]
strict parsing commited fixed the T1000 issues.

still getting the same issue as before with the T2000 with version 1.1.4 from this commit

 ./oort.rb -n T2000
T2000:
Sun Fire T2000 Sun System Firmware Update Hypervisor 1.1.4 OBP 4.20.6 POST 4.20.6
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=122430-06
https://getupdates.oracle.com/all_unsigned/122430-06.zip
Sun Fire T2000 Sun System Firmware Update Hypervisor 1.2.3 OBP 4.23.4 POST 4.23.4
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=123482-03
https://getupdates.oracle.com/all_unsigned/123482-03.zip
./oort.rb:1708:in `readlines': No such file or directory @ rb_sysopen - /Users/me/oort/data/html/123483-01.html (Errno::ENOENT)
	from ./oort.rb:1708:in `get_aru_no'
	from ./oort.rb:1763:in `get_oracle_readme_url'
	from ./oort.rb:1739:in `get_obp_ver'
	from ./oort.rb:2171:in `block in print_output'
	from ./oort.rb:2154:in `each'
	from ./oort.rb:2154:in `print_output'
	from ./oort.rb:2226:in `handle_fw_output'
	from ./oort.rb:2561:in `<main>'

**Comment by richardatlateralblast** [comment]
Update to 1.1.5...

**Comment by WildOne69** [comment]
BUT github only has 1.1.4....

**Comment by richardatlateralblast** [comment]
Should be there now, on the road, push must have failed

**Comment by WildOne69** [comment]
Thank you for fixing everything. 

didnt mean to be a pain but you have SUCH a useful tool i kept wanting to improve on it where possible.

looks like I was the only knuckebrain finding issues...

thanks again.

**Comment by richardatlateralblast** [comment]
No problem, thanks for the testing :)

I don't do much Sun/Oracle work these days so don't get to test it a lot.

**Comment by onewildchild045** [comment]
I'm slowly digging out my Old Sun boxes from storage and starting to set up a lot of my stuff again so I'm poking thru everything and finding the patch numbers and updated EPROMs for older stuff. I haven't done much since Oracle bought Sun and I moved my internet-facing servers to FreeBSD on Dell and Supermicro hardware.

no, I don't have an Oracle account and I'm NOT paying their prices and thanks to your tool I've located a pile of the patches, still looking for others.
